### PR TITLE
Changed to node-friendly raf module

### PR DESCRIPTION
**Pull request by slaskis**
This is the only change I needed to get your awesome [28kb example](https://github.com/matthewmueller/28kb-react-redux-routing) run [with server side rendering](https://github.com/slaskis/28kb-react-redux-routing/tree/isomorphic).

Thanks for these clarifying examples of simple react/redux implementations.

### CODE REVIEW

**Comment by matthewmueller** [comment]
done, thanks! would love to see an example of your server-side rendered example. if you have a standalone, can you open a PR on the 28kb example repo?

**Comment by slaskis** [comment]
Do you mean standalone as more of a "static site" rendering?

Because the branch I linked to has a version which renders it on both the server and client.

**Comment by matthewmueller** [comment]
ohh woops sorry, i missed that haha. i'd just like to make an `examples/` directory at some point and it'd be cool to have an isomorphic example

**Comment by slaskis** [comment]
haha. yeah that sounds like a good idea. I'm assuming you mean in the 28kb repository?

My main issue right now is how the hell to use babel with node. My branch uses babel-node but it seems to not be recommended according to warning signs on their website. But just compiling `server.js` with babel gives me all kinds of issues so I'll just stick with it for now. 

Anyway, since the whole 28k repo is basically a single example (or "boilerplate") as it is right now, should the `examples/` directory be in one of the libraries (such as this one) or maybe separate repositories in a organisation?

**Pull request merged**
